# This is a basic workflow to help you get started with Actions

name: book

on:
  push:
    branches: master
  pull_request:
    branches: master 


jobs:
  
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: pecan/base:latest

    
    steps:
    
    - uses: actions/checkout@v2
        
    - run : | 
         apt-get update \
         && apt-get -y --no-install-recommends install \
         jags \
         time \
         libgdal-dev \
         libglpk-dev \
         librdf0-dev \
         libnetcdf-dev \
         libudunits2-dev \
         libgl1-mesa-dev \
         libglu1-mesa-dev
    
    # Building book from source using makefile
    - name: Building book
      run: cd book_source && make
      
    - name: looking for generated html  
      run: cd /__w/pecan-sandbox/pecan-sandbox/book_source/_book && ls
      shell: bash

    - name: Commiting the changes to pecan documentation repo
      run: |
        git config --global user.email "pecan_bot@example.com"
        git config --global user.name "Mukul Maheshwari"
        git init 
        git add .
        git commit -m "documentation updated by actions"
        git remote add origin https://github.com/MukulMaheshwari/pecan-documentation.git
        git push -u origin master
        
