on:
  issue_comment:
    types: [created]
name: Commands
jobs:
  style:
    if: startsWith(github.event.comment.body, '/style')
    name: style
    runs-on: macOS-latest
    steps:
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
      - name: list changed files
        run: echo '${{ steps.file_changes.outputs.files_modified }}'
      - uses: actions/checkout@v2
      - uses: r-lib/actions/pr-fetch@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: r-lib/actions/setup-r@master
      - name: Install styler
        run: |
          Rscript -e 'install.packages("styler")'
      - name: run styler
        shell: bash
        env:
          FILES: ${{ join(fromJSON(steps.file_changes.outputs.files_modified), ' ') }}
        run: |
          for f in ${FILES}; do
            if [[ "$f" == *.R || "$f" == *.Rmd ]]
              then Rscript -e 'styler::style_file("'${f}'")'
            fi
          done
      - name: commit
        run: |
          git add \*.R
          git add \*.Rmd
          if [ "$(git diff --name-only --cached)" != "" ]; then  git commit -m 'automated syle update' ; fi
      - uses: r-lib/actions/pr-push@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}


  document:
    if: (startsWith(github.event.comment.body, '/style') || startsWith(github.event.comment.body, '/document'))
    runs-on: ubuntu-latest
    container: pecan/depends:develop
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/pr-fetch@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: update dependency lists
        run: Rscript scripts/generate_dependencies.R
      - id: file_changes
        uses: trilom/file-changes-action@v1.2.3
      - id: doc_all
        name: check whether documenting all packages or only changed ones
        if: startsWith(github.event.comment.body, '/document all_packages')
        shell: bash
        run: |
          DESCS=$(find * -name DESCRIPTION | tr '\n' ' ')
          echo "::set-output name=descriptions::${DESCS}"
      - name : make
        shell: bash
        env:
          FILES: ${{ join(fromJSON(steps.file_changes.outputs.files_modified), ' ') }}
          EXTRA_FILES: ${{ steps.doc_all.outputs.descriptions }}
        run: |
          echo ${FILES} ${EXTRA_FILES} \
          | tr ' ' '\n' \
          | grep -e base -e models -e modules \
          | cut -d / -f 1-2 \
          | sort \
          | uniq \
          | xargs -n1 -I{} make .doc/{}
      - name: commit
        run: |
          git config --global user.email "pecan_bot@example.com"
          git config --global user.name "PEcAn stylebot"
          git add \*.Rd \*NAMESPACE Makefile.depends docker/depends/pecan.depends.R
          if [ "$(git diff --name-only --cached)" != "" ]; then  git commit -m 'automated documentation update' ; fi
      - uses: r-lib/actions/pr-push@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
